### ISSUE TITLE
How do I use this

### ISSUE THREAD

**Issue by paganaye** [herberttn/vite-plugin-typescript-transform#2]
Doc Improvement Request: 
I am trying to follow your readme, I made a new app and installed your package.
I am not really sure how to use it to implement the typescript transformer you mention.
Did I miss an example somewhere?
What should I do to make my source code transformed.
https://github.com/paganaye/vite-plugin-one

**Comment by herberttn** [comment]
@paganaye what are you trying to do exactly?
